-- Neotest
vim.keymap.set("n", "<leader>tn", function()
  require("neotest").run.run(vim.fn.expand("%"))
end, { desc = "Run test file (neotest)" })
vim.keymap.set("n", "<leader>tN", function()
  require("neotest").run.run()
end, { desc = "Run nearest test (neotest)" })
vim.keymap.set("n", "<leader>tm", function()
  require("neotest").run.run(vim.fn.getcwd())
end, { desc = "Run all tests (neotest)" })
vim.keymap.set("n", "<leader>tM", function()
  require("neotest").run.run({ suite = true })
end, { desc = "Run whole test suite (neotest)" })
vim.keymap.set("n", "<leader>tD", function()
  require("neotest").run.run({ suite = false, strategy = "dap" })
end, { desc = "Debug test file (neotest)" })
vim.keymap.set("n", "<leader>td", function()
  require("neotest").run.run({ vim.fn.expand("%"), suite = false, strategy = "dap" })
end, { desc = "Debug nearest test (neotest)" })

-- Opencode
vim.keymap.set({ "n", "x" }, "<leader>aoa", function()
  require("opencode").ask("@this: ", { submit = true })
end, { desc = "Ask opencode" })
vim.keymap.set({ "n", "x" }, "<leader>aox", function()
  require("opencode").select()
end, { desc = "Execute opencode action…" })
vim.keymap.set({ "n", "x" }, "<leader>aog", function()
  require("opencode").prompt("@this")
end, { desc = "Add to opencode" })
vim.keymap.set({ "n", "t" }, "<leader>aoo", function()
  require("opencode").toggle()
end, { desc = "Toggle opencode" })
vim.keymap.set("n", "<leader>aok", function()
  require("opencode").command("session.half.page.up")
end, { desc = "opencode half page up" })
vim.keymap.set("n", "<leader>aoj", function()
  require("opencode").command("session.half.page.down")
end, { desc = "opencode half page down" })

-- Snacks
vim.keymap.set("n", "<leader>ss", function()
  require("snacks").picker.grep_word()
end, { desc = "Grep word under cursor" })
